### ISSUE TITLE
Documentación correcta para agregar un producto al pedido

### ISSUE THREAD

**Issue by BrianCraig** [chasqui-ess/chasqui-backend#3]
Hola, Se nescesita poder agregar un producto y una cantidad, a un pedido, pero en la [documentación de la API](http://docs.chasqui.apiary.io/#reference/0/servicios-privados/agregar-producto-al-pedido-individual), los datos del request no tienen relación con "agregar un producto al pedido individual".

Un saludo, Brian.

**Comment by dgonzalia** [comment]
Hola Brian,
Por algun motivo que desconozco no se guardaron los cambios correctamente desde la ultima vez que actualicé apiary. Noté ahora que en el editor eliminaron el botón de Save, y te obligan a guardar y pushear (además de otro cambios menores en su interfaz). Habrán tenido un problema con eso...
